---    
 host_label: jenkins_slaves
 maven_version: 3.2.1
 ant_version: 1.9.4
 forrest_version: 0.9
 clover_version: 2.4.3
 findbugs_version: 2.0.3
 jiracli_version: 2.1.0
 maven_url: http://archive.apache.org/dist/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz
 ant_url: http://www.dsgnwrld.com/am//ant/binaries/apache-ant-{{ant_version}}-bin.tar.gz
 forrest_url: http://archive.apache.org/dist/forrest/{{forrest_version}}/apache-forrest-{{forrest_version}}.tar.gz
 clover_url: http://www.atlassian.com/software/clover/downloads/binary/clover-ant-{{clover_version}}.zip
 findbugs_url: http://sourceforge.net/projects/findbugs/files/findbugs/{{findbugs_version}}/findbugs-{{findbugs_version}}.tar.gz
 jiracli_url: https://bobswift.atlassian.net/wiki/download/attachments/16285777/jira-cli-{{jiracli_version}}-distribution.zip

 jenkins_user: jenkins
 jenkins_home: "/home/jenkins"
 tools_home: "{{jenkins_home}}/tools"
 maven_home: "{{tools_home}}/maven"
 ant_home: "{{tools_home}}/ant"
 forrest_home: "{{tools_home}}/forrest"
 findbugs_home: "{{tools_home}}/findbugs"
 jiracli_home: "{{tools_home}}/jiracli"
 clover_home: "{{tools_home}}/clover"
 m2_cache_dir: "{{jenkins_home}}/.m2"
 buildr_dir: "{{jenkins_home}}/.buildr"
 ssh_dir: "{{jenkins_home}}/.ssh"
