---
  - name: install tools | setup tools dir
    sudo: yes
    sudo_user: jenkins
    file: path={{tools_home}} state=directory owner=jenkins group=jenkins mode=0775

  - name: install tools | setup ant maven forrest tools dir
    sudo: yes
    sudo_user: jenkins
    file: path={{tools_home}}/{{item}} state=directory owner=jenkins group=jenkins mode=0775
    with_items:
      - ant
      - maven
      - forrest
      - clover
      - findbugs
      - jiracli
      
  - name: install tools | Download java.tar.gz
    sudo: yes
    sudo_user: jenkins
    get_url: url={{java_tar_url}} dest={{tools_home}}/java.tar.gz
    when: install_java
    register: get_java

  - name: install tools | Install java.tar.gz
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{tools_home}}/java.tar.gz dest={{tools_home}}
    when: install_java and get_java|changed

  - name: install tools | Install java.tar.gz
    sudo: yes
    sudo_user: jenkins
    file: src={{tools_home}}/java/jdk1.6.0_45-{{jvm_data_model}} 
          dest={{tools_home}}/java/latest state=link 
    when: install_java and get_java|changed


### Download tools 

  - name: install tools | download clover
    sudo: yes
    sudo_user: jenkins
    get_url: url={{clover_url}} dest={{tools_home}}/clover/clover.zip mode=0775
    register: get_clover

  - name: install tools | download maven
    sudo: yes
    sudo_user: jenkins
    get_url: url={{maven_url}} dest={{tools_home}}/maven/maven.tar.gz mode=0775
    register: get_maven

  - name: install tools | download ant
    sudo: yes
    sudo_user: jenkins
    get_url: url={{ant_url}} dest={{tools_home}}/ant/ant.tar.gz mode=0775
    register: get_ant
    
  - name: install tools | download forrest
    sudo: yes
    sudo_user: jenkins
    get_url: url={{forrest_url}} dest={{forrest_home}}/forrest.tar.gz mode=775
    register: get_forrest

  - name: install tools | download findbugs
    sudo: yes
    sudo_user: jenkins
    get_url: url={{findbugs_url}} dest={{findbugs_home}}/findbugs.tar.gz mode=775
    register: get_findbugs
    
  - name: install tools | download jiracli
    sudo: yes
    sudo_user: jenkins
    get_url: url={{jiracli_url}} dest={{jiracli_home}}/jiracli.zip mode=775
    register: get_jiracli

### unarchive tools   

  - name: install tools | untar clover
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{clover_home}}/clover.zip dest={{clover_home}}
    when: get_clover|changed

  - name: install tools | untar maven
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{maven_home}}/maven.tar.gz dest={{maven_home}}
    when: get_maven|changed

  - name: install tools | untar ant
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{ant_home}}/ant.tar.gz dest={{ant_home}}
    when: get_ant|changed

  - name: install tools | untar forrest
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{forrest_home}}/forrest.tar.gz dest={{forrest_home}}
    when: get_forrest|changed

  - name: install tools | untar findbugs
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{findbugs_home}}/findbugs.tar.gz dest={{findbugs_home}}
    when: get_findbugs|changed

  - name: install tools | untar jiracli
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{jiracli_home}}/jiracli.zip dest={{jiracli_home}}
    when: get_jiracli|changed

###symlink -> latest

  - name: install tools | symlink clover -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=clover-ant-{{clover_version}} dest={{clover_home}}/latest state=link
    when: get_clover|changed

  - name: install tools | symlink maven -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-maven-{{maven_version}} dest={{maven_home}}/latest state=link
    when: get_maven|changed

  - name: install tools | symlink maven2 -> latest2
    sudo: yes
    sudo_user: jenkins
    file: src=apache-maven-2.2.1 dest={{maven_home}}/latest2 state=link
    when: get_maven|changed

  - name: install tools | symlink ant -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-ant-{{ant_version}} dest={{ant_home}}/latest state=link
    when: get_ant|changed

  - name: install tools | symlink forrest -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-forrest-{{forrest_version}} dest={{forrest_home}}/latest state=link
    when: get_forrest|changed

  - name: install tools | symlink findbugs -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=findbugs-{{findbugs_version}} dest={{findbugs_home}}/latest state=link
    when: get_findbugs|changed

  - name: install tools | symlink jiracli -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=jira-cli-{{jiracli_version}} dest={{jiracli_home}}/latest state=link
    when: get_jiracli|changed

  - name: install tools | symlink jiracli | jiracli | jira.sh -> jira
    sudo: yes
    sudo_user: jenkins
    file: src={{jiracli_home}}/latest/jira.sh dest={{jiracli_home}}/latest/jira state=link
    when: get_jiracli|changed

## Setup clover license 

  - name: install tools | setup clover license
    sudo: yes
    sudo_user: jenkins
    copy: src={{clover_license_file}} dest={{clover_home}}/latest/lib/clover.license
    when: setup_clover_license


  - name: "Importing asf_internal apt key"
    sudo: yes
    sudo_user: root
    shell: apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 0x7A00258D

  - name: "Adding asf_internal apt repo"
    sudo: yes
    sudo_user: root
    apt_repository: repo='deb https://packages.apache.org/asf_internal trusty main' state=present

  - name: "Install JDK7u79 unlimited security"
    sudo: yes 
    apt: pkg=asf-build-jdk1.7.0-79-unlimited-security state=present update_cache=yes
    register: 7u79

  - name: "Symlink JDK7u79 to /home/jenkins/tools/java"
    sudo: yes
    sudo_user: jenkins
    file: src=/usr/local/jenkins/java/jdk1.7.0_79 dest={{tools_home}}/java/jdk1.7.0_79 state=link
