---
  - name: update_configs | limits.conf
    sudo: yes
    sudo_user: root
    copy: src=limits.conf dest=/etc/security/limits.conf
    tags: update_configs

  - name: update_configs | /etc/pam.d/common-session
    sudo: yes
    sudo_user: root
    copy: src=common-session dest=/etc/pam.d/common-session
    tags: update_configs

  - name: update_configs | settings.xml
    sudo: yes
    sudo_user: jenkins
    template: src=m2_settings.j2 dest={{m2_cache_dir}}/settings.xml
               owner=jenkins group=jenkins 
    when: m2_settings
    tags: update_configs

  - name: update_configs | settings.yaml
    sudo: yes
    sudo_user: jenkins
    template: src=buildr_settings.j2 dest={{buildr_dir}}/settings.yaml
               owner=jenkins group=jenkins 
    when: m2_settings
    tags: update_configs

  - name: update_configs | npmrc
    sudo: yes
    sudo_user: jenkins
    template: src=npmrc.j2 dest={{jenkins_home}}/.npmrc
               owner=jenkins group=jenkins 
    when: npmrc_setup
    tags: update_configs

  - name: update_configs | sshd_config cleanout
    sudo: yes
    sudo_user: root
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^UsePAM\s+no"
                state=absent
    tags: update_configs

  - name: update_configs | sshd_config update
    sudo: yes
    sudo_user: root
    lineinfile: dest=/etc/ssh/sshd_config
                line="UsePAM                          yes"
                state=present
    tags: update_configs
    register: sshd_config_update

  - name: update_configs | sshd restart
    sudo: yes
    sudo_user: root
    service: name=ssh state=restarted
    tags: update_configs
    when: sshd_config_update|changed

  - name: update_configs | remove USERGROUPS_ENAB yes
    sudo: yes
    sudo_user: root
    lineinfile: dest=/etc/login.defs
                regexp="^USERGROUPS_ENAB yes"
                state=absent
    tags: update_configs

  - name: update_configs | set USERGROUPS_ENAB to no
    sudo: yes
    sudo_user: root
    lineinfile: dest=/etc/login.defs
                line="USERGROUPS_ENAB no"
                state=present
    tags: update_configs
